_wandb:
    value:
        cli_version: 0.27.0
        e:
            dl9f1z21alzvz5nc4tnmevpkaco0euoh:
                codePath: train_masked.py
                codePathLocal: train_masked.py
                cpu_count: 8
                cpu_count_logical: 12
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "269975810048"
                        used: "245345431552"
                email: tve23cs061@cet.ac.in
                executable: C:\Users\gayat\OneDrive\Desktop\MyLab\Human-disease-classifier\venv\Scripts\python.exe
                git:
                    commit: d9045fa482d94e24eeff8994c7f806b09cc1672a
                    remote: https://github.com/Gythrie/Human-disease-classifier.git
                gpu: NVIDIA GeForce RTX 3050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2048
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Laptop GPU
                      uuid: GPU-a7a8ab87-d4b2-c9aa-c3ab-ebd0ccfa4a39
                host: Gayathri
                memory:
                    total: "16891633664"
                os: Windows-10-10.0.26200-SP0
                program: C:\Users\gayat\OneDrive\Desktop\MyLab\Human-disease-classifier\train_masked.py
                python: CPython 3.10.11
                root: C:\Users\gayat\OneDrive\Desktop\MyLab\Human-disease-classifier
                startedAt: "2026-05-18T16:35:19.096686Z"
                writerId: dl9f1z21alzvz5nc4tnmevpkaco0euoh
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 41
                - 49
                - 63
            "2":
                - 1
                - 41
                - 49
                - 63
            "3":
                - 2
                - 16
            "4": 3.10.11
            "5": 0.27.0
            "8":
                - 3
            "12": 0.27.0
            "13": windows-amd64
batch_size:
    value: 8
epochs:
    value: 50
learning_rate:
    value: 0.0001
model:
    value: convit_tiny
